[features]
seeds = true
skip-lint = false

[programs.devnet]
aurasci = "AuRa1CiHACkATHONpRoGRamId11111111111111111"

[programs.localnet]
aurasci = "AuRa1CiHACkATHONpRoGRamId11111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"
